#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $
exec dbus-launch --exit-with-session dwm &
feh --bg-fill /home/kieran/Repositories/dotfiles/backgrounds/newbliss.png &
dwmblocks &
exec dwm
