#!/bin/sh

if [ "$(pamixer --get-mute)" = true ]; then
    echo "🔇 "
    exit
fi

vol="$(pamixer --get-volume)"
[ $? -ne 0 ] && [ -z "$vol" ] && exit 1

if [ "$vol" -gt 40 ]; then
    echo " "
elif [ "$vol" -gt 15 ]; then
    echo " "
else
    echo " "
fi
